import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Script 
          src="https://pl29550586.effectivecpmnetwork.com/9c/69/d4/9c69d43a251beb8c8ae9fe3bb6afd082.js"
          strategy="afterInteractive"
        />
        {/* Social Bar */}
        <Script 
          src="https://pl29550588.effectivecpmnetwork.com/60/ea/75/60ea75d44514f8fee7ff0dc279f6d037.js"
          strategy="afterInteractive"
        />
        {children}
      </body>
    </html>
  );
}
